on: push
name: WebseCI
jobs:
  test:
    name: Webse
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 11 Pro Max', ' platform=iOS Simulator,OS=13.1,name=iPad Pro (11-inch)']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          xcodebuild -project Webse.xcodeproj -scheme Webse CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
