name: WebseCI
on:
  watch:
    types: [started]
    branches:
      - master
jobs:  
  test:
    name: Webse
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          xcodebuild -project Webse.xcodeproj -scheme Webse CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" ONLY_ACTIVE_ARCH=NO

